# Generated by Django 5.1.2 on 2024-11-05 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='hod',
        ),
    ]
