# Generated by Django 5.1.2 on 2024-10-28 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_department_hod'),
        ('school', '0001_initial'),
        ('teacher', '0002_teacher_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='dept_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.school'),
        ),
    ]
