# Generated by Django 5.1.2 on 2024-10-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_teacher_dept_name_alter_teacher_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
