# Generated by Django 5.1.2 on 2024-11-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_alter_department_hod'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='dept_name',
            field=models.ManyToManyField(blank=True, related_name='school_department', to='department.department'),
        ),
    ]
