# Generated by Django 5.1.2 on 2024-11-08 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_temp_pass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
