# Generated by Django 5.1.2 on 2024-10-26 16:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0002_department_hod'),
        ('teacher', '0002_teacher_school_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('maths_marks', models.IntegerField()),
                ('physics_marks', models.IntegerField()),
                ('chemistry_marks', models.IntegerField()),
                ('total_marks', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('dept_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='department.department')),
                ('emp_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.teacher')),
            ],
        ),
    ]
