# Generated by Django 5.1.2 on 2024-10-26 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='emp_name',
            new_name='emp_id',
        ),
    ]
